### ISSUE TITLE
Payout script doesn't work 

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/test-templates#13]
Doesn't work for Henry
mining
http://testnet.oracles.org:4000/account/0xc1a5b2e4b842b139f1f57601e0d38b764feb65b0
payout
0x290b4B2c0b60c37f829FD402529A997DBf4B027a

for Jeff:
payout
0x58c47f56905ad6c0ec519f57867be1117dbb3b9e

But works for Roman
payout
0x49c250F3f9D4e1fa2686AaF88427c83C8ef4297b 

They used the same template but on a different time. One day for the cron job passed several times for both Henry and Jeff

Please
- review recent changes, what can cause that bug?
- provide a command for debugging on their host

**Comment by phahulin** [comment]
RPC port was changed, the pull request I created initially was to the wrong branch of oracles-scripts repo.
Now port number is fixed in the correct branch, so they should be able to fix this problem by pulling the latest version. This script can be run from the local machine on which they generated ssh keys:
```
ssh $vm_username@$vm_ip 'cd oracles-scripts && git pull origin alphadevtestnet'
```
something like this should be printed to stdout:
```
From https://github.com/oraclesorg/oracles-scripts
 * branch            alphadevtestnet     -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 scripts/config.json | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

So **for Henry** that would be
```
ssh henryvishnevsky@40.85.155.157 'cd oracles-scripts && git pull origin alphadevtestnet'
```
and **for Jeff**
```
ssh jflowers@52.191.174.156 'cd oracles-scripts && git pull origin alphadevtestnet'
```
