### ISSUE TITLE
Specify key and password in cloud UI 

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/test-templates#4]
Maybe there is a way to specify them in ENV variables?

**Comment by phahulin** [comment]
There is no way to upload a file, among [types available in UI](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates) there are
`secureString` and `secureObject` (for json) that will not be visible in UI after the deployment is [complete](https://docs.microsoft.com/en-us/azure/azure-resource-manager/media/resource-group-authoring-templates/show-parameters.png).

These values can be provided for the script
```
 sh install.sh <password> <file-content>
```
This script is executed on the VM.
Our goal here is to hide these lines as well, so that if someone malicious gains access to the VM he cannot read them from any file, am I right? In such a case we can try
```
INSTALL_PASS=<password> INSTALL_FILE=<file-content> sh install.sh
```
and use `$INSTALL_PASS` and `$INSTALL_FILE` in install.sh

**Comment by igorbarinov** [comment]
We don't need to protect whose files on the file system. Although, home directory encryption for the docker host will be good.

Where will a user specify a password (or id_rsa.pub) for the new docker host?

**Comment by phahulin** [comment]
In the UI that will be used to create new deployment, the user would need to copy-paste his id_rsa.pub [like so](http://take.ms/rT3A2).
For password we can make a _secureString_ field which looks like ******

**Comment by phahulin** [comment]
Done.
